### ISSUE TITLE
lxc would it be possible to change to linuxcontainers.org lxc?

### ISSUE THREAD

**Issue by bmullan** [daniviga/webvirtmgr#10]
LXC comes it two distinct flavors.   One is libvirt-lxc and the other just called lxc.

From what I've read webvirtmgr uses the libvirt-lxc and I was wondering what the possibility might be to adopt the non-libvirt LXC ?

The non-libvirt lxc is widely adopted and  has a well defined API and bindings for multiple languages.

LXC is currently made of a few separate components:
    The liblxc library
    Several language bindings for the API:
      * python3 (in-tree, long term support in 1.0.x)
      * lua (in tree, long term support in 1.0.x)
      * Go
      * ruby
      * python2
      * Haskell

It also includes a set of standard tools to control the containers  
and a wide array of Distribution container templates including Centos, Ubuntu Debian, Oracle etc.
LXC supports both unprivileged & privileged containers, CRIU, "nested" containers etc.

**[linuxcontainers.org](https://linuxcontainers.org/lxc/introduction/)**

LXC is also part of Canonical's efforts with LXD (lexdee) now.   LXD uses a a new LXC RESTful api to provide LXC management both locally and to remote LXC "hosts".    (create, stop, start, delete, clone, etc)

**Comment by daniviga** [comment]
WebVirtMgr relies on libvirt to have a common framework for both QEMU/KVM and LXC. Porting it to the original LXC means rebuilding everything from scratch which is out of the scope for this project which aims to add the LXC support to the originlal WebVirtMgr project, also because I'm only a sysadmin/devops and not a developer.
